# Extra autostart processes
# exec-once = uwsm-app -- my-service
#exec-once = gammastep -O 7500/
#exec-once = ss-local -c ~/dotfiles/.config/shadowsocks/config1.json
#exec-once = ss-local -c ~/dotfiles/.config/shadowsocks/config2.json
#exec-once = ss-local -c ~/dotfiles/.config/shadowsocks/config3.json
#exec-once = ss-local -c ~/dotfiles/.config/shadowsocks/config4.json
