#env = HYPRCURSOR_THEME,"Future-Cyan-Hyprcursor_Theme"
#env = HYPRCURSOR_SIZE,33
#
#env = HYPRCURSOR_THEME,Future-Cyan-Hyprcursor_Theme
#env = XCURSOR_THEME,Future-cyan-cursors
#
# --- ArcAurora ---
env = HYPRCURSOR_THEME,ArcAurora-Hypr
env = XCURSOR_THEME,ArcAurora-cursors
#
# --- ArcStarry ---
# env = HYPRCURSOR_THEME,ArcStarry-Hypr
# env = XCURSOR_THEME,ArcStarry-cursors
#
# --- Clay ---
# env = HYPRCURSOR_THEME,clay-Hypr
# env = XCURSOR_THEME,clay
#
# --- Moga Candy Black ---
# env = HYPRCURSOR_THEME,Moga-Candy-Black-Hypr
# env = XCURSOR_THEME,Moga-Candy-Black
#
#
env = HYPRCURSOR_SIZE,20
env = XCURSOR_SIZE,20
